
export const STOCK_NAMES: Record<string, string> = {
  'NVDA': 'Nvidia, 英偉達',
  'AAPL': 'Apple, 蘋果',
  'MSFT': 'Microsoft, 微軟',
  'GOOGL': 'Alphabet (Google), 谷歌',
  'TSM': 'TSMC, 台積電',
  'AVGO': 'Broadcom, 博通',
  'AMD': 'AMD, 超微半導體',
  'INTC': 'Intel, 英特爾',
  'CSCO': 'Cisco, 思科',
  'IBM': 'IBM, 國際商業機器',
  'ORCL': 'Oracle, 甲骨文',
  'MU': 'Micron, 美光',
  'ASML': 'ASML, 艾司摩爾',
  'ADBE': 'Adobe, 奧多比',
  'META': 'Meta (Facebook), 梅塔',
  'COHR': 'Coherent, 高意',
  'LITE': 'Lumentum, 朗門騰',
  'FN': 'Fabrinet, 嘉里',
  'WDC': 'Western Digital (SanDisk), 威騰電子',
  'ARM': 'Arm Holdings, 安謀',
  'VRT': 'Vertiv, 維諦',
  'EATN': 'Eaton, 伊頓',
  'SMCI': 'Super Micro Computer, 美超微',
  'MRVL': 'Marvell, 邁威爾',
  'CDNS': 'Cadence, 益華電腦',
  'SNPS': 'Synopsys, 新思科技',
  'NXPI': 'NXP, 恩智浦',
  'ADI': 'Analog Devices, 亞德諾',
  'AMZN': 'Amazon (AWS), 亞馬遜',
  'PLTR': 'Palantir, 帕蘭泰爾',
  'SNOW': 'Snowflake, 斯諾弗萊克',
  'ANET': 'Arista Networks, 艾瑞斯塔',
  'DELL': 'Dell Technologies, 戴爾科技',
  'HPE': 'Hewlett Packard Enterprise, 慧與科技',
  'STX': 'Seagate Technology, 希捷科技',
  'PSTG': 'Pure Storage, 普多和儲存',
  'MOD': 'Modine Manufacturing, 摩丁製造',
  'NVT': 'nVent Electric, 恩文特',
  'KLAC': 'KLA Corporation, 科磊',
  'TXN': 'Texas Instruments, 德州儀器',
  'ON': 'onsemi, 安森美',
  'NTAP': 'NetApp, 網安',
  'TER': 'Teradyne, 泰瑞達',
  'AXTI': 'AXT, AXT公司',
  'QCOM': 'Qualcomm, 高通',
  'NOW': 'ServiceNow, 關鍵服務',
  'CRM': 'Salesforce, 賽富時',
  'ISRG': 'Intuitive Surgical, 直覺手術',
  'BSX': 'Boston Scientific, 波士頓科學',
  'ASTS': 'AST SpaceMobile, AST太空行動',
  'RKLB': 'Rocket Lab, 火箭實驗室',
  'GSAT': 'Globalstar, 全球星',
  'LHX': 'L3Harris, L3哈里斯',
  'ALB': 'Albemarle, 雅寶',
  'ENPH': 'Enphase Energy, 安費斯能源',
  'FSLR': 'First Solar, 第一太陽能',
  'PLUG': 'Plug Power, 普拉格能源',
  'TSLA': 'Tesla, 特斯拉',
  'BE': 'Bloom Energy, 布魯姆能源',
  'OKLO': 'Oklo, 奧克洛',
  'GEV': 'GE Vernova, GE維諾瓦',
  'PWR': 'Quanta Services, 廣量服務',
  'IONQ': 'IonQ, IonQ公司',
  'RGTI': 'Rigetti Computing, 里格蒂計算',
  'QBTS': 'D-Wave Quantum, D-Wave量子',
  'HON': 'Honeywell, 漢威聯合',
  'SMR': 'NuScale Power, 紐斯凱爾電力'
};
